### ISSUE TITLE
on 5.5 pass is not found

### ISSUE THREAD

**Issue by a333klm** [RyanSweeney987/UE5_Tut_2_Custom_Shaders#2]
https://github.com/RyanSweeney987/UE5_Tut_2_Custom_Shaders/blob/9422d153753ffa4f8e4a1537acf41bd5c866d83f/Source/UE5_Tut_2_Custom_Shaders/Private/Rendering/CustomSceneViewExtension.cpp#L58

Please have a look there. Pass is not defined, it should be PassId

**Comment by RyanSweeney987** [comment]
Renamed both the UE 5.5 and non UE 5.5 variations of the method to use just "Pass"
